// Progression, achievements catalogue.
//
// PROGRESSION-SYSTEM-DESIGN.md §6.3, ~120 entries spanning every
// game + stream + Discord. Each entry is a small JSON record the
// engine (achievements.js) walks against the progressionEvent stream.
//
// Schema (engine reads these fields):
//   id                  unique slug (used as the KV sub-key)
//   category            'identity' | 'clash' | 'boltbound' | 'board'
//                       | 'quick' | 'stocks' | 'bets' | 'stream'
//                       | 'pets' | 'cross-cutting'
//   title               short display name
//   description         one-line explainer (shown on profile + push)
//   iconKind            sprite hint for the profile renderer
//   rarity              'common' | 'rare' | 'epic' | 'legendary'
//   triggers            array of trigger specs (see §6.1 DSL):
//                         { kind, countAtLeast?, sumAtLeast?, withMeta? }
//                         { allOf: [...] }, { anyOf: [...] }
//   xpReward            grant on unlock (default 50 normal / 200 legendary)
//   badgeId             optional, awards the badge id at unlock (P4)
//   secret              hidden until earned (locked to ~5% of catalogue)
//   seasonId            null = always-on; non-null = season-specific
//
// Migration: legacy aquilo/achievements.js entries get id prefix
// 'legacy.<oldKey>' below so existing unlocks survive the move.

export const ACHIEVEMENTS_CATALOG = [

  // ── IDENTITY + onboarding (8) ───────────────────────────────────
  { id: 'id.first-steps', category: 'identity', title: 'First Steps',
    description: 'Claim your first daily.', iconKind: 'star-sm',
    rarity: 'common', xpReward: 25,
    triggers: [{ kind: 'daily.claimed', countAtLeast: 1 }] },
  { id: 'id.found-your-class', category: 'identity', title: 'Found Your Class',
    description: 'Pick a hero class.', iconKind: 'hero-sword',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'hero.levelup', countAtLeast: 1 }] },
  { id: 'id.linked-up', category: 'identity', title: 'Linked Up',
    description: 'Link one external account.', iconKind: 'link',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'profile.linked', countAtLeast: 1 }] },
  { id: 'id.verified-trio', category: 'identity', title: 'Verified Trio',
    description: 'Link Discord, Twitch, and Steam.', iconKind: 'link-3',
    rarity: 'rare', xpReward: 100, badgeId: 'verified-trio',
    triggers: [
      { kind: 'profile.linked', withMeta: { platform: 'twitch' }, countAtLeast: 1 },
      { kind: 'profile.linked', withMeta: { platform: 'steam' }, countAtLeast: 1 },
    ] },
  { id: 'id.profile-curator', category: 'identity', title: 'Profile Curator',
    description: 'Set your bio, badge showcase, and privacy setting.', iconKind: 'pencil',
    rarity: 'common', xpReward: 30,
    triggers: [{ kind: 'profile.curated', countAtLeast: 1 }] },
  { id: 'id.streak-7', category: 'identity', title: '7-Day Streak',
    description: 'Daily check-in 7 days in a row.', iconKind: 'flame-sm',
    rarity: 'common', xpReward: 75, badgeId: 'streak-7',
    triggers: [{ kind: 'daily.streak.7', countAtLeast: 1 }] },
  { id: 'id.streak-30', category: 'identity', title: '30-Day Streak',
    description: 'Daily check-in 30 days.', iconKind: 'flame-md',
    rarity: 'rare', xpReward: 150, badgeId: 'streak-30',
    triggers: [{ kind: 'daily.streak.30', countAtLeast: 1 }] },
  { id: 'id.streak-100', category: 'identity', title: '100-Day Streak',
    description: 'Daily check-in 100 days.', iconKind: 'flame-lg',
    rarity: 'legendary', xpReward: 500, badgeId: 'streak-100',
    triggers: [{ kind: 'daily.streak.100', countAtLeast: 1 }] },

  // ── CLASH (25) ──────────────────────────────────────────────────
  { id: 'clash.first-raid', category: 'clash', title: 'First Raid',
    description: 'Run your first Clash raid.', iconKind: 'clash-shield',
    rarity: 'common', xpReward: 30,
    triggers: [{ kind: 'clash.raid.played', countAtLeast: 1 }] },
  { id: 'clash.first-three-star', category: 'clash', title: 'Three-Star Raider',
    description: 'Land your first 3-star raid.', iconKind: 'star-3',
    rarity: 'rare', xpReward: 100, badgeId: 'three-star-raider',
    triggers: [{ kind: 'clash.raid.won.3', countAtLeast: 1 }] },
  { id: 'clash.raid-10', category: 'clash', title: 'Raiding Regular',
    description: 'Run 10 raids.', iconKind: 'clash-shield', rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'clash.raid.played', countAtLeast: 10 }] },
  { id: 'clash.raid-100', category: 'clash', title: 'Hundred Raider',
    description: 'Run 100 raids.', iconKind: 'clash-shield', rarity: 'rare', xpReward: 150, badgeId: 'hundred-raider',
    triggers: [{ kind: 'clash.raid.played', countAtLeast: 100 }] },
  { id: 'clash.raid-1000', category: 'clash', title: 'Thousand Raider',
    description: 'Run 1,000 raids.', iconKind: 'clash-shield', rarity: 'legendary', xpReward: 500, badgeId: 'thousand-raider',
    triggers: [{ kind: 'clash.raid.played', countAtLeast: 1000 }] },
  { id: 'clash.three-star-25', category: 'clash', title: 'Star Specialist',
    description: 'Land 25 three-star raids.', iconKind: 'star-3', rarity: 'rare', xpReward: 200,
    triggers: [{ kind: 'clash.raid.won.3', countAtLeast: 25 }] },
  { id: 'clash.three-star-100', category: 'clash', title: 'Star Authority',
    description: 'Land 100 three-star raids.', iconKind: 'star-3', rarity: 'epic', xpReward: 400, badgeId: 'star-authority',
    triggers: [{ kind: 'clash.raid.won.3', countAtLeast: 100 }] },
  { id: 'clash.defender', category: 'clash', title: 'Defender',
    description: 'Successfully defend your town against a raid.', iconKind: 'shield-up', rarity: 'common', xpReward: 40,
    triggers: [{ anyOf: [{ kind: 'clash.defended.goblin', countAtLeast: 1 }, { kind: 'clash.defended.pvp', countAtLeast: 1 }] }] },
  { id: 'clash.goblin-slayer', category: 'clash', title: 'Goblin Slayer',
    description: 'Repel 10 goblin raids.', iconKind: 'goblin', rarity: 'rare', xpReward: 100,
    triggers: [{ kind: 'clash.defended.goblin', countAtLeast: 10 }] },
  { id: 'clash.goblin-slayer-100', category: 'clash', title: 'Goblin Bane',
    description: 'Repel 100 goblin raids.', iconKind: 'goblin', rarity: 'epic', xpReward: 300, badgeId: 'goblin-bane',
    triggers: [{ kind: 'clash.defended.goblin', countAtLeast: 100 }] },
  { id: 'clash.king-slayer', category: 'clash', title: 'King Slayer',
    description: 'Slay a Goblin King during a Warband raid.', iconKind: 'crown',
    rarity: 'epic', xpReward: 350, badgeId: 'king-slayer', secret: true,
    triggers: [{ kind: 'clash.defended.goblin', withMeta: { mode: 'warband' }, countAtLeast: 1 }] },
  { id: 'clash.wyrm-slayer', category: 'clash', title: 'Wyrm Slayer',
    description: 'Slay a Wyrm during a TH10 Warband.', iconKind: 'wyrm',
    rarity: 'legendary', xpReward: 800, badgeId: 'wyrm-slayer', secret: true,
    triggers: [{ kind: 'clash.defended.goblin', withMeta: { wyrm: true }, countAtLeast: 1 }] },
  { id: 'clash.donate-5k', category: 'clash', title: 'Community Patron',
    description: 'Donate 5,000 bolts to the town treasury.', iconKind: 'coin', rarity: 'common', xpReward: 60,
    triggers: [{ kind: 'clash.donated', sumAtLeast: { metaField: 'bolts', value: 5000 } }] },
  { id: 'clash.donate-50k', category: 'clash', title: 'Town Pillar',
    description: 'Donate 50,000 bolts.', iconKind: 'coin', rarity: 'rare', xpReward: 200,
    triggers: [{ kind: 'clash.donated', sumAtLeast: { metaField: 'bolts', value: 50000 } }] },
  { id: 'clash.donate-500k', category: 'clash', title: 'Town Founder',
    description: 'Donate 500,000 bolts.', iconKind: 'coin', rarity: 'legendary', xpReward: 800, badgeId: 'town-founder',
    triggers: [{ kind: 'clash.donated', sumAtLeast: { metaField: 'bolts', value: 500000 } }] },
  { id: 'clash.pvp-defended-10', category: 'clash', title: 'Wall Bearer',
    description: 'Defend 10 PvP raids.', iconKind: 'shield-up', rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'clash.defended.pvp', countAtLeast: 10 }] },
  { id: 'clash.win-1', category: 'clash', title: 'First Win',
    description: 'Clear a raid (any star count).', iconKind: 'star-1', rarity: 'common', xpReward: 25,
    triggers: [{ anyOf: [
      { kind: 'clash.raid.won.1', countAtLeast: 1 },
      { kind: 'clash.raid.won.2', countAtLeast: 1 },
      { kind: 'clash.raid.won.3', countAtLeast: 1 },
    ] }] },
  { id: 'clash.warband-survivor', category: 'clash', title: 'Warband Survivor',
    description: 'Repel a Warband boss raid.', iconKind: 'goblin-king', rarity: 'epic', xpReward: 300,
    triggers: [{ kind: 'clash.defended.goblin', withMeta: { mode: 'warband' }, countAtLeast: 1 }] },
  { id: 'clash.scrap-collector', category: 'clash', title: 'Scrap Collector',
    description: 'Run 50 raids of any kind.', iconKind: 'clash-shield', rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'clash.raid.played', countAtLeast: 50 }] },
  { id: 'clash.goblin-grinder', category: 'clash', title: 'Goblin Grinder',
    description: 'Repel 50 goblin raids.', iconKind: 'goblin', rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'clash.defended.goblin', countAtLeast: 50 }] },
  { id: 'clash.master-architect', category: 'clash', title: 'Master Architect',
    description: 'Have your town reach Town Hall L5.', iconKind: 'townhall',
    rarity: 'rare', xpReward: 150, badgeId: 'master-architect',
    triggers: [{ kind: 'clash.town.th-reached', withMeta: { th: 5 }, countAtLeast: 1 }] },
  { id: 'clash.high-architect', category: 'clash', title: 'High Architect',
    description: 'Town Hall L10.', iconKind: 'townhall',
    rarity: 'legendary', xpReward: 800, badgeId: 'high-architect',
    triggers: [{ kind: 'clash.town.th-reached', withMeta: { th: 10 }, countAtLeast: 1 }] },
  { id: 'clash.repair-50', category: 'clash', title: 'Repair Crew',
    description: 'Repair 50 buildings.', iconKind: 'wrench', rarity: 'rare', xpReward: 100,
    triggers: [{ kind: 'clash.building.repaired', countAtLeast: 50 }] },
  { id: 'clash.three-star-streak', category: 'clash', title: 'Streak of Stars',
    description: 'Land 5 three-star raids in a row.', iconKind: 'star-3',
    rarity: 'epic', xpReward: 300, secret: true,
    triggers: [{ kind: 'clash.raid.streak3', countAtLeast: 1 }] },
  { id: 'clash.war-hero', category: 'clash', title: 'War Hero',
    description: 'Win 5 community wars.', iconKind: 'banner',
    rarity: 'epic', xpReward: 400, badgeId: 'war-hero',
    triggers: [{ kind: 'clash.war.won', countAtLeast: 5 }] },

  // ── BOLTBOUND (22) ───────────────────────────────────────────────
  { id: 'cards.first-match', category: 'boltbound', title: 'First Match',
    description: 'Play your first Boltbound match.', iconKind: 'boltbound-card',
    rarity: 'common', xpReward: 30,
    triggers: [{ kind: 'cards.match.played', countAtLeast: 1 }] },
  { id: 'cards.first-pack', category: 'boltbound', title: 'First Pack',
    description: 'Open your first card pack.', iconKind: 'pack',
    rarity: 'common', xpReward: 30,
    triggers: [{ kind: 'cards.pack.opened', countAtLeast: 1 }] },
  { id: 'cards.collector-100', category: 'boltbound', title: 'Collector',
    description: 'Collect 100 cards.', iconKind: 'pack',
    rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'cards.pack.opened', countAtLeast: 20 }] },
  { id: 'cards.collector-500', category: 'boltbound', title: 'Hoarder',
    description: 'Collect 500 cards.', iconKind: 'pack',
    rarity: 'rare', xpReward: 200,
    triggers: [{ kind: 'cards.pack.opened', countAtLeast: 100 }] },
  { id: 'cards.full-set', category: 'boltbound', title: 'Set Completion',
    description: 'Collect the full 1,170-card set.', iconKind: 'pack',
    rarity: 'legendary', xpReward: 1000, badgeId: 'full-set',
    triggers: [{ kind: 'cards.set.completed', countAtLeast: 1 }] },
  { id: 'cards.legendary-pull', category: 'boltbound', title: 'Legendary Pull',
    description: 'Pull a legendary from a pack.', iconKind: 'star-lg',
    rarity: 'rare', xpReward: 100,
    triggers: [{ kind: 'cards.pack.opened', withMeta: { hadLegendary: true }, countAtLeast: 1 }] },
  { id: 'cards.legendary-10', category: 'boltbound', title: 'Legend Magnet',
    description: 'Pull 10 legendaries.', iconKind: 'star-lg',
    rarity: 'epic', xpReward: 300, badgeId: 'legend-magnet',
    triggers: [{ kind: 'cards.pack.opened', withMeta: { hadLegendary: true }, countAtLeast: 10 }] },
  { id: 'cards.craft-1', category: 'boltbound', title: 'First Craft',
    description: 'Craft a pack from fragments.', iconKind: 'gear', rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'cards.crafted', countAtLeast: 1 }] },
  { id: 'cards.craft-50', category: 'boltbound', title: 'Master Crafter',
    description: 'Craft 50 packs from fragments.', iconKind: 'gear', rarity: 'rare', xpReward: 200, badgeId: 'master-crafter',
    triggers: [{ kind: 'cards.crafted', countAtLeast: 50 }] },
  { id: 'cards.deck-builder', category: 'boltbound', title: 'Deck Architect',
    description: 'Build 5 distinct decks.', iconKind: 'deck',
    rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'cards.deck.built', countAtLeast: 5 }] },
  { id: 'cards.pvp-1', category: 'boltbound', title: 'PvP Initiate',
    description: 'Win a Boltbound PvP match.', iconKind: 'duel-cards',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'cards.match.won.pvp', countAtLeast: 1 }] },
  { id: 'cards.pvp-10', category: 'boltbound', title: 'PvP Regular',
    description: 'Win 10 PvP matches.', iconKind: 'duel-cards',
    rarity: 'common', xpReward: 100,
    triggers: [{ kind: 'cards.match.won.pvp', countAtLeast: 10 }] },
  { id: 'cards.pvp-50', category: 'boltbound', title: 'PvP Champion',
    description: 'Win 50 PvP matches.', iconKind: 'duel-cards',
    rarity: 'rare', xpReward: 250, badgeId: 'pvp-champion',
    triggers: [{ kind: 'cards.match.won.pvp', countAtLeast: 50 }] },
  { id: 'cards.pvp-250', category: 'boltbound', title: 'PvP Master',
    description: 'Win 250 PvP matches.', iconKind: 'duel-cards',
    rarity: 'epic', xpReward: 500, badgeId: 'pvp-master',
    triggers: [{ kind: 'cards.match.won.pvp', countAtLeast: 250 }] },
  { id: 'cards.match-100', category: 'boltbound', title: 'Match Veteran',
    description: 'Play 100 matches.', iconKind: 'boltbound-card', rarity: 'common', xpReward: 100,
    triggers: [{ kind: 'cards.match.played', countAtLeast: 100 }] },
  { id: 'cards.aggro-10', category: 'boltbound', title: 'Aggro Specialist',
    description: 'Win 10 matches with aggro decks.', iconKind: 'fire',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'cards.match.won.pvp', withMeta: { archetype: 'aggro' }, countAtLeast: 10 }] },
  { id: 'cards.control-10', category: 'boltbound', title: 'Control Specialist',
    description: 'Win 10 matches with control decks.', iconKind: 'frost',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'cards.match.won.pvp', withMeta: { archetype: 'control' }, countAtLeast: 10 }] },
  { id: 'cards.midrange-10', category: 'boltbound', title: 'Midrange Specialist',
    description: 'Win 10 matches with midrange decks.', iconKind: 'sword',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'cards.match.won.pvp', withMeta: { archetype: 'midrange' }, countAtLeast: 10 }] },
  { id: 'cards.swarm-10', category: 'boltbound', title: 'Swarm Specialist',
    description: 'Win 10 matches with swarm decks.', iconKind: 'group',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'cards.match.won.pvp', withMeta: { archetype: 'swarm' }, countAtLeast: 10 }] },
  { id: 'cards.archetype-master', category: 'boltbound', title: 'Archetype Master',
    description: 'Win 10 matches in each of aggro/control/midrange/swarm/burn.', iconKind: 'star-lg',
    rarity: 'legendary', xpReward: 800, badgeId: 'archetype-master',
    triggers: [
      { kind: 'cards.match.won.pvp', withMeta: { archetype: 'aggro' }, countAtLeast: 10 },
      { kind: 'cards.match.won.pvp', withMeta: { archetype: 'control' }, countAtLeast: 10 },
      { kind: 'cards.match.won.pvp', withMeta: { archetype: 'midrange' }, countAtLeast: 10 },
      { kind: 'cards.match.won.pvp', withMeta: { archetype: 'swarm' }, countAtLeast: 10 },
      { kind: 'cards.match.won.pvp', withMeta: { archetype: 'burn' }, countAtLeast: 10 },
    ] },
  { id: 'cards.speedrun', category: 'boltbound', title: 'Speedrun',
    description: 'Win a match in 5 turns or fewer.', iconKind: 'lightning',
    rarity: 'rare', xpReward: 100, secret: true,
    triggers: [{ kind: 'cards.match.won.pvp', withMeta: { fastWin: true }, countAtLeast: 1 }] },
  { id: 'cards.comeback', category: 'boltbound', title: 'Comeback King',
    description: 'Win a match after dropping below 5 HP.', iconKind: 'heart',
    rarity: 'epic', xpReward: 200, secret: true,
    triggers: [{ kind: 'cards.match.won.pvp', withMeta: { comeback: true }, countAtLeast: 1 }] },

  // ── BOARD GAMES (12) ─────────────────────────────────────────────
  { id: 'board.first-move', category: 'board', title: 'First Move',
    description: 'Play a board game match.', iconKind: 'board-pawn',
    rarity: 'common', xpReward: 30,
    triggers: [{ kind: 'board.match.played', countAtLeast: 1 }] },
  { id: 'board.chess-10', category: 'board', title: 'Chess Initiate',
    description: 'Win 10 chess games.', iconKind: 'chess-king',
    rarity: 'common', xpReward: 100,
    triggers: [{ kind: 'board.match.won', withMeta: { game: 'chess' }, countAtLeast: 10 }] },
  { id: 'board.chess-100', category: 'board', title: 'Chess Grandmaster',
    description: 'Win 100 chess games.', iconKind: 'chess-king',
    rarity: 'epic', xpReward: 400, badgeId: 'chess-grandmaster',
    triggers: [{ kind: 'board.match.won', withMeta: { game: 'chess' }, countAtLeast: 100 }] },
  { id: 'board.checkers-10', category: 'board', title: 'Checkers Initiate',
    description: 'Win 10 checkers games.', iconKind: 'checker',
    rarity: 'common', xpReward: 100,
    triggers: [{ kind: 'board.match.won', withMeta: { game: 'checkers' }, countAtLeast: 10 }] },
  { id: 'board.checkers-100', category: 'board', title: 'Checkers Master',
    description: 'Win 100 checkers games.', iconKind: 'checker',
    rarity: 'epic', xpReward: 400, badgeId: 'checkers-master',
    triggers: [{ kind: 'board.match.won', withMeta: { game: 'checkers' }, countAtLeast: 100 }] },
  { id: 'board.connect4-10', category: 'board', title: 'Four-in-a-Row',
    description: 'Win 10 connect-4 games.', iconKind: 'connect4',
    rarity: 'common', xpReward: 100,
    triggers: [{ kind: 'board.match.won', withMeta: { game: 'connect4' }, countAtLeast: 10 }] },
  { id: 'board.connect4-100', category: 'board', title: 'Connect Master',
    description: 'Win 100 connect-4 games.', iconKind: 'connect4',
    rarity: 'epic', xpReward: 400, badgeId: 'connect-master',
    triggers: [{ kind: 'board.match.won', withMeta: { game: 'connect4' }, countAtLeast: 100 }] },
  { id: 'board.triple-threat', category: 'board', title: 'Triple Threat',
    description: 'Win at least one match in chess, checkers, and connect-4.', iconKind: 'board-pawn',
    rarity: 'rare', xpReward: 200, badgeId: 'triple-threat',
    triggers: [
      { kind: 'board.match.won', withMeta: { game: 'chess' }, countAtLeast: 1 },
      { kind: 'board.match.won', withMeta: { game: 'checkers' }, countAtLeast: 1 },
      { kind: 'board.match.won', withMeta: { game: 'connect4' }, countAtLeast: 1 },
    ] },
  { id: 'board.streak-5', category: 'board', title: 'On Fire',
    description: 'Win 5 board games in a row.', iconKind: 'flame-sm',
    rarity: 'rare', xpReward: 150, secret: true,
    triggers: [{ kind: 'board.match.streak5', countAtLeast: 1 }] },
  { id: 'board.played-50', category: 'board', title: 'Board Regular',
    description: 'Play 50 board games.', iconKind: 'board-pawn',
    rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'board.match.played', countAtLeast: 50 }] },
  { id: 'board.won-500', category: 'board', title: 'Board Veteran',
    description: 'Win 500 board games.', iconKind: 'board-pawn',
    rarity: 'legendary', xpReward: 800, badgeId: 'board-veteran',
    triggers: [{ kind: 'board.match.won', countAtLeast: 500 }] },
  { id: 'board.upset', category: 'board', title: 'Upset',
    description: 'Beat a higher-level player in a board game.', iconKind: 'lightning',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'board.match.won', withMeta: { upset: true }, countAtLeast: 1 }] },

  // ── QUICK GAMES (12) ─────────────────────────────────────────────
  { id: 'quick.first-play', category: 'quick', title: 'First Hand',
    description: 'Play any quick game.', iconKind: 'quick-dice',
    rarity: 'common', xpReward: 25,
    triggers: [{ kind: 'quick.game.played', countAtLeast: 1 }] },
  { id: 'quick.lucky-7', category: 'quick', title: 'Lucky Number Seven',
    description: '7 quick-game wins.', iconKind: 'quick-dice',
    rarity: 'common', xpReward: 60,
    triggers: [{ kind: 'quick.game.bigwin', countAtLeast: 7 }] },
  { id: 'quick.big-win', category: 'quick', title: 'Big Win',
    description: 'A single payout > 10× stake.', iconKind: 'star-lg',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'quick.game.bigwin', withMeta: { mult: 10 }, countAtLeast: 1 }] },
  { id: 'quick.blackjack-50', category: 'quick', title: 'Blackjack Pro',
    description: '50 blackjack wins.', iconKind: 'cards',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'quick.game.bigwin', withMeta: { game: 'blackjack' }, countAtLeast: 50 }] },
  { id: 'quick.roulette-3', category: 'quick', title: 'Roulette Streak',
    description: 'Win 3 roulette spins in a row.', iconKind: 'wheel',
    rarity: 'common', xpReward: 75, secret: true,
    triggers: [{ kind: 'quick.roulette.streak3', countAtLeast: 1 }] },
  { id: 'quick.high-roller', category: 'quick', title: 'High Roller',
    description: 'Place a single bet of 1,000 bolts or more.', iconKind: 'coin',
    rarity: 'rare', xpReward: 100,
    triggers: [{ kind: 'quick.game.played', withMeta: { bet: 1000 }, countAtLeast: 1 }] },
  { id: 'quick.crash-2x', category: 'quick', title: 'Crash Survivor',
    description: 'Cash out a crash run at 2× or higher.', iconKind: 'crash',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'quick.game.played', withMeta: { game: 'crash', mult: 2 }, countAtLeast: 1 }] },
  { id: 'quick.mines-clear', category: 'quick', title: 'Minesweeper',
    description: 'Clear a mines board with 5+ tiles revealed.', iconKind: 'mine',
    rarity: 'rare', xpReward: 100,
    triggers: [{ kind: 'quick.game.played', withMeta: { game: 'mines', reveals: 5 }, countAtLeast: 1 }] },
  { id: 'quick.hilo-streak', category: 'quick', title: 'Hi-Lo Streak',
    description: 'Hit 5 correct guesses in a row in hi-lo.', iconKind: 'arrows',
    rarity: 'rare', xpReward: 100,
    triggers: [{ kind: 'quick.game.played', withMeta: { game: 'hilo', steps: 5 }, countAtLeast: 1 }] },
  { id: 'quick.played-100', category: 'quick', title: 'Quick-game Regular',
    description: 'Play 100 quick games.', iconKind: 'quick-dice',
    rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'quick.game.played', countAtLeast: 100 }] },
  { id: 'quick.played-1000', category: 'quick', title: 'Quick-game Veteran',
    description: 'Play 1,000 quick games.', iconKind: 'quick-dice',
    rarity: 'epic', xpReward: 300, badgeId: 'quick-veteran',
    triggers: [{ kind: 'quick.game.played', countAtLeast: 1000 }] },
  { id: 'quick.allgames', category: 'quick', title: 'Game-Show Host',
    description: 'Play every quick game at least once.', iconKind: 'quick-dice',
    rarity: 'rare', xpReward: 150, badgeId: 'game-show-host',
    triggers: [
      { kind: 'quick.game.played', withMeta: { game: 'blackjack' }, countAtLeast: 1 },
      { kind: 'quick.game.played', withMeta: { game: 'roulette' }, countAtLeast: 1 },
      { kind: 'quick.game.played', withMeta: { game: 'wheel' }, countAtLeast: 1 },
      { kind: 'quick.game.played', withMeta: { game: 'hilo' }, countAtLeast: 1 },
      { kind: 'quick.game.played', withMeta: { game: 'mines' }, countAtLeast: 1 },
      { kind: 'quick.game.played', withMeta: { game: 'plinko' }, countAtLeast: 1 },
    ] },

  // ── STOCKS + BETTING (15) ────────────────────────────────────────
  { id: 'stocks.first-trade', category: 'stocks', title: 'First Trade',
    description: 'Buy your first stock.', iconKind: 'stocks-chart',
    rarity: 'common', xpReward: 25,
    triggers: [{ kind: 'stocks.trade', countAtLeast: 1 }] },
  { id: 'stocks.diversified', category: 'stocks', title: 'Diversified',
    description: 'Hold 5 different tickers at once.', iconKind: 'stocks-chart',
    rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'stocks.portfolio.diversified', countAtLeast: 1 }] },
  { id: 'stocks.bullmarket', category: 'stocks', title: 'Bull Market',
    description: 'Portfolio value crosses +20%.', iconKind: 'arrow-up',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'stocks.portfolio.up20', countAtLeast: 1 }] },
  { id: 'stocks.bagholder', category: 'stocks', title: 'Bagholder',
    description: 'Hold a position through a -25% drawdown.', iconKind: 'arrow-down',
    rarity: 'rare', xpReward: 75, secret: true,
    triggers: [{ kind: 'stocks.portfolio.down25', countAtLeast: 1 }] },
  { id: 'stocks.trade-100', category: 'stocks', title: 'Day Trader',
    description: '100 stock trades.', iconKind: 'stocks-chart',
    rarity: 'rare', xpReward: 200, badgeId: 'day-trader',
    triggers: [{ kind: 'stocks.trade', countAtLeast: 100 }] },
  { id: 'bet.first', category: 'bets', title: 'First Bet',
    description: 'Place your first sports bet.', iconKind: 'bet-ticket',
    rarity: 'common', xpReward: 25,
    triggers: [{ kind: 'bet.placed', countAtLeast: 1 }] },
  { id: 'bet.first-win', category: 'bets', title: 'First Win',
    description: 'Win a sports bet.', iconKind: 'bet-ticket',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'bet.won', countAtLeast: 1 }] },
  { id: 'bet.parlay-win', category: 'bets', title: 'Parlay Champion',
    description: 'Win a 5-leg or longer parlay.', iconKind: 'star-lg',
    rarity: 'epic', xpReward: 400, badgeId: 'parlay-champion',
    triggers: [{ kind: 'bet.won.parlay', withMeta: { legs: 5 }, countAtLeast: 1 }] },
  { id: 'bet.parlay-any', category: 'bets', title: 'Parlay Player',
    description: 'Win any parlay.', iconKind: 'bet-ticket',
    rarity: 'rare', xpReward: 100,
    triggers: [{ kind: 'bet.won.parlay', countAtLeast: 1 }] },
  { id: 'bet.underdog', category: 'bets', title: 'Underdog Story',
    description: 'Win a bet on a +200 line or worse.', iconKind: 'bet-ticket',
    rarity: 'rare', xpReward: 150,
    triggers: [{ kind: 'bet.won', withMeta: { odds: 200 }, countAtLeast: 1 }] },
  { id: 'bet.nfl', category: 'bets', title: 'Touchdown',
    description: 'Win an NFL bet.', iconKind: 'football',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'bet.won', withMeta: { sport: 'NFL' }, countAtLeast: 1 }] },
  { id: 'bet.nba', category: 'bets', title: 'Buzzer Beater',
    description: 'Win an NBA bet.', iconKind: 'basketball',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'bet.won', withMeta: { sport: 'NBA' }, countAtLeast: 1 }] },
  { id: 'bet.mlb', category: 'bets', title: 'Walk-Off',
    description: 'Win an MLB bet.', iconKind: 'baseball',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'bet.won', withMeta: { sport: 'MLB' }, countAtLeast: 1 }] },
  { id: 'bet.nhl', category: 'bets', title: 'Power Play',
    description: 'Win an NHL bet.', iconKind: 'hockey',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'bet.won', withMeta: { sport: 'NHL' }, countAtLeast: 1 }] },
  { id: 'bet.streak-5', category: 'bets', title: 'Hot Hand',
    description: 'Win 5 bets in a row.', iconKind: 'flame-sm',
    rarity: 'epic', xpReward: 250, badgeId: 'hot-hand',
    triggers: [{ kind: 'bet.streak5', countAtLeast: 1 }] },

  // ── STREAM + COMMUNITY (14) ──────────────────────────────────────
  { id: 'stream.first-checkin', category: 'stream', title: 'First Check-In',
    description: 'Check in to your first stream.', iconKind: 'stream',
    rarity: 'common', xpReward: 30,
    triggers: [{ kind: 'stream.checkin', countAtLeast: 1 }] },
  { id: 'stream.checkin-10', category: 'stream', title: 'Regular Viewer',
    description: 'Check in to 10 streams.', iconKind: 'stream',
    rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'stream.checkin', countAtLeast: 10 }] },
  { id: 'stream.checkin-50', category: 'stream', title: 'Loyal Viewer',
    description: 'Check in to 50 streams.', iconKind: 'stream',
    rarity: 'rare', xpReward: 200, badgeId: 'loyal-viewer',
    triggers: [{ kind: 'stream.checkin', countAtLeast: 50 }] },
  { id: 'stream.checkin-200', category: 'stream', title: 'Pillar of the Community',
    description: '200 stream check-ins.', iconKind: 'stream',
    rarity: 'legendary', xpReward: 800, badgeId: 'community-pillar',
    triggers: [{ kind: 'stream.checkin', countAtLeast: 200 }] },
  { id: 'stream.watched-24h', category: 'stream', title: 'Watching',
    description: 'Watch 24 cumulative stream hours.', iconKind: 'stream',
    rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'stream.watched.1h', countAtLeast: 24 }] },
  { id: 'stream.watched-100h', category: 'stream', title: 'Devoted',
    description: 'Watch 100 cumulative stream hours.', iconKind: 'stream',
    rarity: 'rare', xpReward: 200,
    triggers: [{ kind: 'stream.watched.1h', countAtLeast: 100 }] },
  { id: 'stream.cheer-1', category: 'stream', title: 'Cheer',
    description: 'First cheer in chat.', iconKind: 'cheer',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'stream.cheer', countAtLeast: 1 }] },
  { id: 'stream.cheer-100', category: 'stream', title: 'Cheerleader',
    description: '100 cheers.', iconKind: 'cheer',
    rarity: 'rare', xpReward: 200, badgeId: 'cheerleader',
    triggers: [{ kind: 'stream.cheer', countAtLeast: 100 }] },
  { id: 'discord.chatty-1000', category: 'stream', title: 'Chatty',
    description: '1,000 Discord messages.', iconKind: 'speech',
    rarity: 'common', xpReward: 100,
    triggers: [{ kind: 'discord.message', countAtLeast: 1000 }] },
  { id: 'discord.chatty-10000', category: 'stream', title: 'Conversationalist',
    description: '10,000 Discord messages.', iconKind: 'speech',
    rarity: 'rare', xpReward: 300, badgeId: 'conversationalist',
    triggers: [{ kind: 'discord.message', countAtLeast: 10000 }] },
  { id: 'community.vote-10', category: 'stream', title: 'Voter',
    description: 'Vote in 10 community polls.', iconKind: 'ballot',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'community.vote', countAtLeast: 10 }] },
  { id: 'stream.subscriber', category: 'stream', title: 'Subscriber',
    description: 'Linked Twitch subscriber.', iconKind: 'sub',
    rarity: 'rare', xpReward: 150, badgeId: 'subscriber',
    triggers: [{ kind: 'profile.linked', withMeta: { platform: 'twitch', sub: true }, countAtLeast: 1 }] },
  { id: 'stream.patron', category: 'stream', title: 'Patron',
    description: 'Active Patreon supporter.', iconKind: 'sub',
    rarity: 'rare', xpReward: 200, badgeId: 'patron',
    triggers: [{ kind: 'profile.linked', withMeta: { platform: 'patreon' }, countAtLeast: 1 }] },
  { id: 'community.first-friend', category: 'stream', title: 'First Friend',
    description: 'Add your first friend.', iconKind: 'friends',
    rarity: 'common', xpReward: 30,
    triggers: [{ kind: 'profile.friend.accepted', countAtLeast: 1 }] },

  // ── PETS (6) ─────────────────────────────────────────────────────
  { id: 'pet.first', category: 'pets', title: 'First Friend',
    description: 'Tame your first pet.', iconKind: 'pet-paw',
    rarity: 'common', xpReward: 50,
    triggers: [{ kind: 'pet.tamed', countAtLeast: 1 }] },
  { id: 'pet.menagerie-4', category: 'pets', title: 'Pet Lover',
    description: 'Tame 4 different species.', iconKind: 'pet-paw',
    rarity: 'common', xpReward: 100,
    triggers: [{ kind: 'pet.tamed.distinct', sumAtLeast: { metaField: 'species', value: 4 } }] },
  { id: 'pet.menagerie-8', category: 'pets', title: 'Menagerie',
    description: 'Tame 8 different species.', iconKind: 'pet-paw',
    rarity: 'rare', xpReward: 200, badgeId: 'menagerie',
    triggers: [{ kind: 'pet.tamed.distinct', sumAtLeast: { metaField: 'species', value: 8 } }] },
  { id: 'pet.legendary', category: 'pets', title: 'Legendary Pet',
    description: 'Tame a legendary pet.', iconKind: 'star-lg',
    rarity: 'epic', xpReward: 400, badgeId: 'legendary-pet',
    triggers: [{ kind: 'pet.tamed', withMeta: { rarity: 'legendary' }, countAtLeast: 1 }] },
  { id: 'pet.fed-50', category: 'pets', title: 'Caretaker',
    description: 'Feed your pet 50 times.', iconKind: 'pet-paw',
    rarity: 'common', xpReward: 75,
    triggers: [{ kind: 'pet.fed', countAtLeast: 50 }] },
  { id: 'pet.fed-365', category: 'pets', title: 'Lifelong Bond',
    description: 'Feed your pet 365 times.', iconKind: 'pet-paw',
    rarity: 'epic', xpReward: 300, badgeId: 'lifelong-bond',
    triggers: [{ kind: 'pet.fed', countAtLeast: 365 }] },

  // ── CROSS-CUTTING + META (6) ─────────────────────────────────────
  { id: 'meta.polyglot', category: 'cross-cutting', title: 'Polyglot',
    description: 'Play every game type, Clash + Boltbound + board + quick.', iconKind: 'star-lg',
    rarity: 'rare', xpReward: 200, badgeId: 'polyglot',
    triggers: [
      { kind: 'clash.raid.played', countAtLeast: 1 },
      { kind: 'cards.match.played', countAtLeast: 1 },
      { kind: 'board.match.played', countAtLeast: 1 },
      { kind: 'quick.game.played', countAtLeast: 1 },
    ] },
  { id: 'meta.renaissance', category: 'cross-cutting', title: 'Renaissance Player',
    description: 'Win at least once in every game type.', iconKind: 'star-lg',
    rarity: 'epic', xpReward: 500, badgeId: 'renaissance',
    triggers: [
      { anyOf: [
        { kind: 'clash.raid.won.1', countAtLeast: 1 },
        { kind: 'clash.raid.won.2', countAtLeast: 1 },
        { kind: 'clash.raid.won.3', countAtLeast: 1 },
      ] },
      { anyOf: [
        { kind: 'cards.match.won.pvp', countAtLeast: 1 },
        { kind: 'cards.match.won.npc', countAtLeast: 1 },
      ] },
      { kind: 'board.match.won', countAtLeast: 1 },
      { kind: 'quick.game.bigwin', countAtLeast: 1 },
    ] },
  { id: 'meta.level-25', category: 'cross-cutting', title: 'Top of the Class',
    description: 'Reach account level 25.', iconKind: 'star-lg',
    rarity: 'rare', xpReward: 200, badgeId: 'level-25',
    triggers: [{ kind: 'level.reached', withMeta: { level: 25 }, countAtLeast: 1 }] },
  { id: 'meta.level-50', category: 'cross-cutting', title: 'Veteran',
    description: 'Reach account level 50.', iconKind: 'star-lg',
    rarity: 'epic', xpReward: 500, badgeId: 'level-50',
    triggers: [{ kind: 'level.reached', withMeta: { level: 50 }, countAtLeast: 1 }] },
  { id: 'meta.level-100', category: 'cross-cutting', title: 'Living Legend',
    description: 'Reach account level 100.', iconKind: 'star-lg',
    rarity: 'legendary', xpReward: 2000, badgeId: 'level-100',
    triggers: [{ kind: 'level.reached', withMeta: { level: 100 }, countAtLeast: 1 }] },
  { id: 'meta.hunter-50', category: 'cross-cutting', title: 'Achievement Hunter',
    description: 'Unlock 50 achievements.', iconKind: 'trophy',
    rarity: 'rare', xpReward: 250, badgeId: 'achievement-hunter',
    triggers: [{ kind: 'achievement.unlocked', countAtLeast: 50 }] },
  { id: 'meta.hunter-100', category: 'cross-cutting', title: 'Trophy Cabinet',
    description: 'Unlock 100 achievements.', iconKind: 'trophy',
    rarity: 'legendary', xpReward: 1000, badgeId: 'trophy-cabinet',
    triggers: [{ kind: 'achievement.unlocked', countAtLeast: 100 }] },
];

// Build a lookup map by id (for the engine + UI lookups).
export const ACHIEVEMENTS_BY_ID = Object.fromEntries(
  ACHIEVEMENTS_CATALOG.map(a => [a.id, a])
);

// Index of trigger-kind -> [achId, ...] so the engine doesn't have to
// scan the whole catalogue on every event. Built once at import time.
export const ACHIEVEMENTS_BY_TRIGGER_KIND = (() => {
  const idx = {};
  function visit(spec, achId) {
    if (!spec) return;
    if (spec.kind) {
      idx[spec.kind] = idx[spec.kind] || [];
      if (!idx[spec.kind].includes(achId)) idx[spec.kind].push(achId);
    }
    if (Array.isArray(spec.allOf)) for (const s of spec.allOf) visit(s, achId);
    if (Array.isArray(spec.anyOf)) for (const s of spec.anyOf) visit(s, achId);
  }
  for (const a of ACHIEVEMENTS_CATALOG) {
    for (const t of (a.triggers || [])) visit(t, a.id);
  }
  return idx;
})();
