// Tiny pure-JS PNG codec for the character/pet render endpoint.
//
// Scope: decode + encode 8-bit RGBA non-interlaced PNGs. Every sprite
// in aquilo-gg/sprites/ is generated by tools/build-sprites.ps1 with
// GDI+ Format32bppArgb, which writes exactly this PNG shape (color
// type 6, bit depth 8, interlace 0, single IDAT). We don't need a
// general-purpose decoder — we control the inputs.
//
// Compression: zlib (deflate with adler32 wrapper). Cloudflare
// Workers expose DecompressionStream('deflate') for decode and
// CompressionStream('deflate') for encode. No npm dep.
//
// Reference: https://www.w3.org/TR/PNG/

const PNG_SIG = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

// CRC-32 (PNG uses Ethernet polynomial, reflected, init 0xFFFFFFFF).
// Table is computed once at module load.
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
    }
    t[n] = c >>> 0;
  }
  return t;
})();
function crc32(bytes, start = 0, end = bytes.length) {
  let c = 0xffffffff;
  for (let i = start; i < end; i++) c = CRC_TABLE[(c ^ bytes[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function readU32BE(b, o) {
  return (b[o] * 0x1000000) + ((b[o + 1] << 16) | (b[o + 2] << 8) | b[o + 3]);
}
function writeU32BE(b, o, v) {
  b[o] = (v >>> 24) & 0xff;
  b[o + 1] = (v >>> 16) & 0xff;
  b[o + 2] = (v >>> 8) & 0xff;
  b[o + 3] = v & 0xff;
}

// Decompress zlib (deflate + 2-byte header + 4-byte adler32 trailer)
// using the browser/Worker DecompressionStream. The 'deflate' stream
// expects zlib framing, which is exactly what PNG IDAT carries.
async function inflate(zlibBytes) {
  const ds = new DecompressionStream('deflate');
  const writer = ds.writable.getWriter();
  writer.write(zlibBytes);
  writer.close();
  const chunks = [];
  const reader = ds.readable.getReader();
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }
  return concat(chunks);
}

async function deflate(rawBytes) {
  const cs = new CompressionStream('deflate');
  const writer = cs.writable.getWriter();
  writer.write(rawBytes);
  writer.close();
  const chunks = [];
  const reader = cs.readable.getReader();
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }
  return concat(chunks);
}

function concat(chunks) {
  let total = 0;
  for (const c of chunks) total += c.byteLength;
  const out = new Uint8Array(total);
  let off = 0;
  for (const c of chunks) { out.set(c, off); off += c.byteLength; }
  return out;
}

// PNG filter reversal — Paeth predictor and friends.
// Filter byte sits at the start of every row in the unfiltered stream.
function paeth(a, b, c) {
  const p = a + b - c;
  const pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  if (pb <= pc) return b;
  return c;
}

// Decode a single PNG buffer → { width, height, pixels: Uint8Array }
// pixels is RGBA row-major (h × w × 4 bytes).
export async function decodePng(buf) {
  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
  if (bytes.length < 8) throw new Error('png: too short');
  for (let i = 0; i < 8; i++) {
    if (bytes[i] !== PNG_SIG[i]) throw new Error('png: bad signature');
  }

  let width = 0, height = 0, colorType = 0, bitDepth = 0;
  const idatChunks = [];

  let p = 8;
  while (p < bytes.length) {
    const len = readU32BE(bytes, p);
    const type = String.fromCharCode(bytes[p + 4], bytes[p + 5], bytes[p + 6], bytes[p + 7]);
    const dataStart = p + 8;
    const dataEnd = dataStart + len;
    if (type === 'IHDR') {
      width  = readU32BE(bytes, dataStart);
      height = readU32BE(bytes, dataStart + 4);
      bitDepth  = bytes[dataStart + 8];
      colorType = bytes[dataStart + 9];
    } else if (type === 'IDAT') {
      idatChunks.push(bytes.subarray(dataStart, dataEnd));
    } else if (type === 'IEND') {
      break;
    }
    p = dataEnd + 4;   // skip CRC
  }

  if (bitDepth !== 8 || colorType !== 6) {
    throw new Error('png: only 8-bit RGBA supported (got bitDepth=' + bitDepth + ' colorType=' + colorType + ')');
  }
  if (!width || !height) throw new Error('png: missing IHDR');

  const compressed = concat(idatChunks);
  const raw = await inflate(compressed);

  const bpp = 4;                     // bytes per pixel
  const stride = width * bpp;
  const pixels = new Uint8Array(width * height * bpp);

  // Reverse per-row filter. PNG filter codes:
  //   0 None, 1 Sub, 2 Up, 3 Average, 4 Paeth.
  let off = 0;
  for (let y = 0; y < height; y++) {
    const filter = raw[off++];
    const rowStart = y * stride;
    if (filter === 0) {
      pixels.set(raw.subarray(off, off + stride), rowStart);
    } else if (filter === 1) {
      // Sub: x + a
      for (let x = 0; x < stride; x++) {
        const a = x >= bpp ? pixels[rowStart + x - bpp] : 0;
        pixels[rowStart + x] = (raw[off + x] + a) & 0xff;
      }
    } else if (filter === 2) {
      // Up: x + b
      for (let x = 0; x < stride; x++) {
        const b = y > 0 ? pixels[rowStart - stride + x] : 0;
        pixels[rowStart + x] = (raw[off + x] + b) & 0xff;
      }
    } else if (filter === 3) {
      // Average: x + (a + b) / 2
      for (let x = 0; x < stride; x++) {
        const a = x >= bpp ? pixels[rowStart + x - bpp] : 0;
        const b = y > 0 ? pixels[rowStart - stride + x] : 0;
        pixels[rowStart + x] = (raw[off + x] + ((a + b) >> 1)) & 0xff;
      }
    } else if (filter === 4) {
      // Paeth: x + Paeth(a, b, c)
      for (let x = 0; x < stride; x++) {
        const a = x >= bpp ? pixels[rowStart + x - bpp] : 0;
        const b = y > 0 ? pixels[rowStart - stride + x] : 0;
        const c = (y > 0 && x >= bpp) ? pixels[rowStart - stride + x - bpp] : 0;
        pixels[rowStart + x] = (raw[off + x] + paeth(a, b, c)) & 0xff;
      }
    } else {
      throw new Error('png: unknown filter ' + filter);
    }
    off += stride;
  }

  return { width, height, pixels };
}

// Encode { width, height, pixels } back to a PNG buffer. Uses filter
// 0 (None) for every row — simplest, slightly larger files. For
// 40×56 pixel sprites the size cost is negligible (a few hundred
// bytes vs a few dozen).
export async function encodePng(image) {
  const { width, height, pixels } = image;
  if (!width || !height) throw new Error('png: encode missing dims');
  const bpp = 4;
  const stride = width * bpp;
  // Build pre-compress buffer with filter byte per row.
  const raw = new Uint8Array(height * (stride + 1));
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0;          // filter: None
    raw.set(pixels.subarray(y * stride, (y + 1) * stride), y * (stride + 1) + 1);
  }
  const compressed = await deflate(raw);

  // Build PNG chunks: IHDR, IDAT, IEND.
  const ihdr = new Uint8Array(13);
  writeU32BE(ihdr, 0, width);
  writeU32BE(ihdr, 4, height);
  ihdr[8]  = 8;   // bit depth
  ihdr[9]  = 6;   // color type RGBA
  ihdr[10] = 0;   // compression
  ihdr[11] = 0;   // filter
  ihdr[12] = 0;   // interlace

  const parts = [];
  parts.push(PNG_SIG);
  parts.push(buildChunk('IHDR', ihdr));
  parts.push(buildChunk('IDAT', compressed));
  parts.push(buildChunk('IEND', new Uint8Array(0)));
  return concat(parts);
}

function buildChunk(type, data) {
  const out = new Uint8Array(4 + 4 + data.length + 4);
  writeU32BE(out, 0, data.length);
  out[4] = type.charCodeAt(0);
  out[5] = type.charCodeAt(1);
  out[6] = type.charCodeAt(2);
  out[7] = type.charCodeAt(3);
  out.set(data, 8);
  const crc = crc32(out, 4, 8 + data.length);
  writeU32BE(out, 8 + data.length, crc);
  return out;
}

// ── Compositor ───────────────────────────────────────────────────
//
// Layers are an array of decoded images, drawn in order (back to
// front). Every layer must share the same dimensions. Source-over
// alpha blend per pixel.
export function compose(layers) {
  if (!layers.length) throw new Error('compose: no layers');
  const { width, height } = layers[0];
  for (const l of layers) {
    if (l.width !== width || l.height !== height) {
      throw new Error('compose: layer dims mismatch');
    }
  }
  const out = new Uint8Array(width * height * 4);
  for (const layer of layers) {
    const src = layer.pixels;
    for (let i = 0; i < out.length; i += 4) {
      const sa = src[i + 3];
      if (sa === 0) continue;
      const da = out[i + 3];
      if (sa === 255 || da === 0) {
        out[i]     = src[i];
        out[i + 1] = src[i + 1];
        out[i + 2] = src[i + 2];
        out[i + 3] = sa;
      } else {
        // src-over alpha composite
        const sA = sa / 255;
        const dA = da / 255;
        const outA = sA + dA * (1 - sA);
        if (outA === 0) continue;
        out[i]     = Math.round((src[i]     * sA + out[i]     * dA * (1 - sA)) / outA);
        out[i + 1] = Math.round((src[i + 1] * sA + out[i + 1] * dA * (1 - sA)) / outA);
        out[i + 2] = Math.round((src[i + 2] * sA + out[i + 2] * dA * (1 - sA)) / outA);
        out[i + 3] = Math.round(outA * 255);
      }
    }
  }
  return { width, height, pixels: out };
}

// ── Palette swap ─────────────────────────────────────────────────
//
// Hair, eyes, accents are authored at ONE colour and palette-swapped
// at render time so we don't have to ship 12 × 14 hair-style ×
// hair-colour permutations.
//
// `paletteMap` is an array of `{ from: [r,g,b], to: [r,g,b] }`.
// Pixels whose RGB exactly matches `from` get rewritten to `to`
// (alpha preserved). Tolerance is intentionally 0 — sprites authored
// with the generator are colour-disciplined and exact-match is the
// fastest pass.
export function paletteSwap(image, paletteMap) {
  const out = {
    width: image.width,
    height: image.height,
    pixels: new Uint8Array(image.pixels),    // copy
  };
  for (let i = 0; i < out.pixels.length; i += 4) {
    if (out.pixels[i + 3] === 0) continue;
    const r = out.pixels[i], g = out.pixels[i + 1], b = out.pixels[i + 2];
    for (const m of paletteMap) {
      if (r === m.from[0] && g === m.from[1] && b === m.from[2]) {
        out.pixels[i]     = m.to[0];
        out.pixels[i + 1] = m.to[1];
        out.pixels[i + 2] = m.to[2];
        break;
      }
    }
  }
  return out;
}
